spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/outbox_pattern
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    jdbc:
      dialect: mysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type: true
        use_sql_comments: true


  application:
    name: OrderService

server:
  port: 8083

integration:
  deliveryService:
    url: ${DELIVERY_SERVICE_URL:http://localhost:8081/api/v1}

retryabletask:
  timeoutInSeconds: 36000
  limit: 100