spring:

  datasource:
    username: root
    password: sleepyroot
    url: jdbc:mysql://localhost:3306/outboxpattern
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    jdbc:
      dialect: mysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  application:
    name: OrderService
